
import { GoogleGenAI } from "@google/genai";
import { Lang } from "../lib/i18n";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY is not defined in environment variables");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const model = 'gemini-2.5-flash';

const languageMap: Record<Lang, string> = {
  en: "English",
  ru: "Russian",
  zh: "Chinese",
};

export const analyzeCoffeeCup = async (imageData: string, mimeType: string, focusArea: string, language: Lang): Promise<string> => {
  try {
    const languageName = languageMap[language];
    const systemInstruction = `You are a wise and insightful psychologist who uses the ancient art of coffee ground reading for deep personality analysis. Your task is not to predict the future, but to help the person understand themselves better. Your response must be in ${languageName}.`;

    let focusInstruction = '';
    switch (focusArea) {
      case 'career':
        focusInstruction = 'When analyzing, focus on career, professional development, ambitions, and self-realization.';
        break;
      case 'relationships':
        focusInstruction = 'When analyzing, focus on personal relationships, love, friendship, and interactions with loved ones.';
        break;
      default: // 'wellbeing'
        focusInstruction = 'Conduct a comprehensive analysis covering the general emotional state, inner resources, and life balance.';
        break;
    }

    const structurePrompt = `Carefully study the provided image of the coffee grounds in the cup. Your analysis must include:
1.  **Key Symbols and Figures**: Describe what you see.
2.  **Psychological Interpretation**: Explain what these symbols might mean in the context of the chosen theme.
3.  **Conclusions and Recommendations**: Formulate gentle and supportive advice to help the person on their path.

Your response should be structured, profound, and written in a calm, therapeutic tone. Avoid categorical predictions. Instead, use metaphorical and suggestive language that encourages self-reflection. Format your response using Markdown for better readability: use headings, lists, and text emphasis.`;
    
    const prompt = `${focusInstruction}\n\n${structurePrompt}`;

    const imagePart = {
      inlineData: {
        data: imageData,
        mimeType: mimeType,
      },
    };

    const textPart = {
      text: prompt,
    };

    const response = await ai.models.generateContent({
      model: model,
      contents: { parts: [imagePart, textPart] },
      config: {
        systemInstruction: systemInstruction,
      }
    });

    return response.text;
  } catch (error) {
    console.error("Error calling Gemini API:", error);
    throw new Error("Failed to get analysis from Gemini API.");
  }
};

// Fix: Add the missing `generateLogo` function to resolve the import error in LogoLab.tsx.
export const generateLogo = async (prompt: string): Promise<string> => {
  try {
    const response = await ai.models.generateImages({
      model: 'imagen-4.0-generate-001',
      prompt: prompt,
      config: {
        numberOfImages: 1,
        outputMimeType: 'image/png',
        aspectRatio: '1:1',
      },
    });

    if (response.generatedImages && response.generatedImages.length > 0 && response.generatedImages[0].image?.imageBytes) {
      const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
      const imageUrl = `data:image/png;base64,${base64ImageBytes}`;
      return imageUrl;
    }
    throw new Error('No image was generated by the API.');
  } catch (error) {
    console.error(`Error generating logo with prompt "${prompt}":`, error);
    throw new Error("Failed to generate logo from Gemini API.");
  }
};
