/**
 * Referral deep-link payload parsing
 *
 * Telegram deep links of the form `t.me/<bot>?start=ref_<code>` deliver the
 * start payload to grammY via `ctx.match`. This module extracts and validates
 * the referral code from that payload.
 *
 * @module modules/referrals/parse
 */

/** Prefix used in deep-link start payloads for referral codes. */
const REF_PREFIX = "ref_";

/**
 * Referral codes are generated by `get_or_create_referral_code` as 8-char
 * uppercase alphanumeric strings. We accept 1..32 chars of [A-Z0-9] to stay
 * forward-compatible while rejecting anything obviously malformed.
 */
const CODE_PATTERN = /^[A-Z0-9]{1,32}$/;

/**
 * Parse a referral code from a Telegram start payload.
 *
 * Rules:
 * - Input is trimmed of surrounding whitespace.
 * - Only payloads starting with `ref_` are considered referral payloads.
 * - The part after `ref_` must match `[A-Z0-9]{1,32}`, otherwise `null`.
 * - Any other input (empty, undefined, unrelated payload) yields `null`.
 *
 * Note: validation is strict (no normalization/uppercasing). A payload like
 * `ref_abc!@#` contains invalid characters and returns `null` rather than
 * being "cleaned", to avoid silently capturing an incorrect code.
 *
 * @param payload - Raw start payload (grammY `ctx.match`)
 * @returns The validated referral code, or `null` if not a valid ref payload
 */
export function parseRefPayload(payload: string | undefined | null): string | null {
  if (typeof payload !== "string") {
    return null;
  }

  const trimmed = payload.trim();

  if (!trimmed.startsWith(REF_PREFIX)) {
    return null;
  }

  const code = trimmed.slice(REF_PREFIX.length);

  if (!CODE_PATTERN.test(code)) {
    return null;
  }

  return code;
}
