-- Migration: 20260104000000_create_daily_insights.sql
-- Purpose: Create daily_insights table for personalized AI-generated daily insights
-- Feature: Personalized Daily Insights (Spec 009)

-- ============================================================================
-- TABLE: daily_insights
-- Stores personalized morning advice and evening insights generated by AI
-- One record per user per day, with separate fields for morning and evening
-- ============================================================================

CREATE TABLE IF NOT EXISTS daily_insights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  unified_user_id UUID NOT NULL REFERENCES unified_users(id) ON DELETE CASCADE,
  date DATE NOT NULL DEFAULT CURRENT_DATE,

  -- Morning advice (generated at ~8:00 user local time)
  morning_advice TEXT,
  morning_advice_short TEXT, -- First 100 chars for teaser/notification preview
  morning_sent_at TIMESTAMPTZ,
  morning_tokens_used INTEGER DEFAULT 0,

  -- Evening insight (generated at ~20:00 user local time)
  evening_insight TEXT,
  evening_insight_short TEXT, -- First 100 chars for teaser/notification preview
  evening_sent_at TIMESTAMPTZ,
  evening_tokens_used INTEGER DEFAULT 0,

  -- Context used for generation (for debugging/analytics)
  -- Structure: {
  --   "message_ids": ["uuid1", "uuid2", ...],
  --   "memory_ids": ["uuid1", "uuid2", ...],
  --   "last_analysis_id": "uuid" | null
  -- }
  context_data JSONB DEFAULT '{}',

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- One insight record per user per day
  UNIQUE(unified_user_id, date)
);

-- Add table comment for documentation
COMMENT ON TABLE daily_insights IS 'Personalized AI-generated daily insights (morning advice + evening reflection) per user per day';
COMMENT ON COLUMN daily_insights.morning_advice IS 'Full morning advice text generated by AI';
COMMENT ON COLUMN daily_insights.morning_advice_short IS 'First 100 chars of morning advice for notification preview/teaser';
COMMENT ON COLUMN daily_insights.evening_insight IS 'Full evening insight text generated by AI';
COMMENT ON COLUMN daily_insights.evening_insight_short IS 'First 100 chars of evening insight for notification preview/teaser';
COMMENT ON COLUMN daily_insights.context_data IS 'JSON with message_ids, memory_ids, and last_analysis_id used for generation';

-- ============================================================================
-- INDEX: Fast lookup by user and date (most common query pattern)
-- DESC on date ensures recent insights are retrieved first
-- ============================================================================
CREATE INDEX idx_daily_insights_user_date
  ON daily_insights(unified_user_id, date DESC);

-- ============================================================================
-- TRIGGER: Auto-update updated_at timestamp
-- Reuses existing update_updated_at_column() function from prior migrations
-- ============================================================================
CREATE TRIGGER update_daily_insights_updated_at
  BEFORE UPDATE ON daily_insights
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- RLS POLICIES
-- Enable row-level security for multi-tenant data isolation
-- ============================================================================
ALTER TABLE daily_insights ENABLE ROW LEVEL SECURITY;

-- Policy 1: Users can read their own insights via auth.uid()
-- This works for web users authenticated via Supabase Auth
-- Note: Wrapping auth.uid() in (SELECT ...) prevents per-row re-evaluation
CREATE POLICY "Users can read own insights" ON daily_insights
  FOR SELECT USING (
    unified_user_id IN (
      SELECT id FROM unified_users
      WHERE auth_id = (SELECT auth.uid())
    )
  );

-- Policy 2: Service role has full access for background jobs
-- Background workers use service_role key to generate and insert insights
CREATE POLICY "Service role full access" ON daily_insights
  FOR ALL USING ((SELECT auth.role()) = 'service_role');

-- Policy 3: Telegram JWT users can read their own insights
-- Custom JWTs issued for Telegram users contain telegram_user_id claim
-- Note: Wrapping auth.jwt() in (SELECT ...) prevents per-row re-evaluation
CREATE POLICY "Telegram users can read own insights" ON daily_insights
  FOR SELECT USING (
    unified_user_id IN (
      SELECT id FROM unified_users
      WHERE telegram_id = ((SELECT auth.jwt()) ->> 'telegram_user_id')::bigint
    )
  );
